# Generated by Django 4.2.4 on 2023-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type1',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='', max_length=25),
        ),
    ]
